### ISSUE TITLE
Upgrade to Payload V3

### ISSUE THREAD

**Issue by teharris1** [anthonylavado/haaska#5]
Since v2 is now depreciated, what would it take to upgrade to V3? I see that bkryza has done some work on this [https://github.com/bkryza/haaska](https://github.com/bkryza/haaska).

**Comment by anthonylavado** [comment]
Honestly, I’m just starting to learn Python, so it would take me a while to get anything up to speed.

My personal commitment is to try and maintain a repo that is up to date. If @bkryza is already refactoring, then that may be the fork to watch.

@bkryza - since you haven’t enabled issues, would you be willing to pair up and merge efforts? We can also work towards removing the fork relationship from the original so we show up in search results.
